### ISSUE TITLE
New Contact not saved

### ISSUE THREAD

**Issue by tigoe** [ethoinformatics/ethoinfo-project-app#40]
I thought we had an issue already on this, but couldn't find it. This is a biggie we've discussed a lot, never written down, it seems: When you create a new contact in a new diary, it's not saved.

Steps to reproduce:
1. Create a diary, or open one
2. Create a contact
3. name it
4. fill in all option menus
5. Click "Create"

Where'd it go?

**Comment by tigoe** [comment]
Still getting this error with the latest build (pulled from repo Aug 8). 

This time, when I open it in the JS console, I get the following error when I create a new contact:

```
Object {domainName: "diary", beginTime: 1470690412990, endTime: null, eventDate: "2016-08-08", observerId: "user-Tom"…}
bundle.js:81480 Object {domainName: "contact", beginTime: 1470690490040, endTime: null, title: "this is what you want", taxon: "taxon-Aotus"…}beginTime: 1470690490040domainName: "contact"endTime: nullobserverId: "user-Tom"samplingProtocol: nullsubjectId: "animal-group-Callicebus K"taxon: "taxon-Aotus"title: "this is what you want"__proto__: Object
bundle.js:79564 error in CreateNewDialog
bundle.js:79565 TypeError: Cannot read property 'uuid' of undefined(…)(anonymous function) @ bundle.js:79565_rejected @ bundle.js:71099(anonymous function) @ bundle.js:71125when @ bundle.js:71377Promise.promise.promiseDispatch @ bundle.js:71043(anonymous function) @ bundle.js:70859runSingle @ bundle.js:70392flush @ bundle.js:70380
```

**Comment by jcousins** [comment]
I assume you updated project and framework and ran bundler.js in the project dir?

**Comment by tigoe** [comment]
Yes. And used anonymous browsing and made sure there was no history. Working in Chrome.  Here's a more full dump.

```
Object {domainName: "contact", beginTime: 1470693888940, endTime: null, title: "harhah", taxon: "taxon-Aotus"…}beginTime: 1470693888940domainName: "contact"endTime: nullobserverId: "user-Tom"samplingProtocol: nullsubjectId: "animal-group-Callicebus B"taxon: "taxon-Aotus"title: "harhah"__proto__: Object
bundle.js:79564 error in CreateNewDialog
bundle.js:79565 TypeError: Cannot read property 'uuid' of undefined
    at CrudManager.self.addToParent (http://localhost:8000/bundle.js:78550:39)
    at CreateSelectDialog.<anonymous> (http://localhost:8000/bundle.js:81481:21)
    at CreateSelectDialog.EventEmitter.emit (http://localhost:8000/bundle.js:82569:17)
    at CreateNewDialog.<anonymous> (http://localhost:8000/bundle.js:79651:9)
    at CreateNewDialog.EventEmitter.emit (http://localhost:8000/bundle.js:82569:17)
    at http://localhost:8000/bundle.js:79561:10
    at _fulfilled (http://localhost:8000/bundle.js:71089:54)
    at self.promiseDispatch.done (http://localhost:8000/bundle.js:71118:30)
    at Promise.promise.promiseDispatch (http://localhost:8000/bundle.js:71051:13)
    at http://localhost:8000/bundle.js:70859:44(anonymous function) @ bundle.js:79565_rejected @ bundle.js:71099(anonymous function) @ bundle.js:71125when @ bundle.js:71377Promise.promise.promiseDispatch @ bundle.js:71043(anonymous function) @ bundle.js:70859runSingle @ bundle.js:70392flush @ bundle.js:70380
bundle.js:79089 success Mon Aug 08 2016 18:05:17 GMT-0400 (EDT)
```

**Comment by jcousins** [comment]
Does it make the new Contact?

**Comment by tigoe** [comment]
According to the error messages, it seems to, but it never shows up in the app.

t.

**Comment by jcousins** [comment]
Even when it reloads and all that?

BTW, I don't get a uuid error.

**Comment by tigoe** [comment]
Even then. I even tried wiping out my entire repo, still has no luck. The uuid error is very consistent for me. Maybe there is something in your cache that addressed it but didn't find its way into the repo?  

FWIW:
tigoe:~ tigoe$ node -v
v5.4.1
tigoe:~ tigoe$ cordova -v
6.3.0
tigoe:~ tigoe$ npm -v
3.3.12

I'm not running the cordova version so that's less relevant, but are these the same for you?
